
TRAINING:
  EPOCHS: 5
  OPTIMIZER:
    NAME: BertAdamW
    LEARNING_RATE: 0.01
    OPTIM_WEIGHT_DECAY: 1e-4
    OPTIM_EPS: 1e-8
    OPTIM_MOMENTUM: 0.9
    OPTIM_BETA1: 0.9
    OPTIM_BETA2: 0.999
    OPTIM_AMSGRAD: false
    CORRECT_BLAS: true
  SCHEDULER:
    NAME: warmup_linear
    LEARNING_RATE_SCHEDULE_WARMUP_STEP_RATIO: 0.0
